title: Scary Heroes dev blog
author: scaryheroes
email:
description: > # this means to ignore newlines until "baseurl:"
 DevBlog for Scary Heroes and Super Losers, a high fantasy hero management game.

twitter_username: scaryheroes
github_username:  scaryheroes

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - TODO.md
  - about.md

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
